### ISSUE TITLE
Images didnt show

### ISSUE THREAD

**Issue by iamephyz** [shubham-vartak/Society-Management-System#1]
The images on the pages didnt show up, i checked the code and saw the mistake, he used "img" as the directory name instead of "images"

**Comment by shubham-vartak** [comment]
Yes thank you for looking into this and finding a issue. Actually when I
developed this project in my local system i made directory named img so
according to that it was img and due to some technical reasons I had
manually uploaded the images named in images directory so that created this
issue of images soon I will be updating it till then you can change it and
use it or else you can create a pull request..!!

Thanks & Regards
Shubham Vartak

**Comment by iamephyz** [comment]
Nice work you did, well I've not logged in cuz your database section is a
bit complex, according to your handbook one needs to create a database for
each section.

A single database would have been better, with database tables for each
section.

Then we can have a uniform connection.php file that works on all pages.

Either way, kudos on the work you put in.

I was looking for a project that manages users,

- user registers entering information such as state, business name, next of
kin etc.
- admin login and dashboard to manage users according to state of origin or
type of business.
- automatic user generated code to identity each user( like a serial number
or national ID, perhaps 8 or 10 digits hexadecimal).
- user annual subscription, with a payment modal, then a redirect to the
payment completion page and payment status, changed to "PAID".

- User complaints and support page

**Comment by shubham-vartak** [comment]
Thanks that's very helpful feedback actually this project was done by me in
my academic section under bsc program when my knowledge base was weak but
known by seeing this project in current time i also get shocked that how
complex implementation i had done..!!
But as soon as I get time I will try to refractor it and also optimise the
code..!!
It was nice talking to you and once again thanks for review on this
project..!!

Thanks & Regards
Shubham Vartak
